site_name: The Internals of Unity Catalog
site_url: https://books.japila.pl/unity-catalog-internals
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of Unity Catalog

repo_name: GitHub
repo_url: https://github.com/japila-books/unity-catalog-internals
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2026 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: material/github
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate
    # https://squidfunk.github.io/mkdocs-material/upgrade/#contentcodecopy
    - content.code.copy
    # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-path
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# https://squidfunk.github.io/mkdocs-material/customization/#additional-css
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

plugins:
  # https://lukasgeiter.github.io/mkdocs-awesome-nav/migration-v3/
  - awesome-nav
  - macros
  # https://squidfunk.github.io/mkdocs-material/reference/#built-in-meta-plugin
  - meta
  - minify:
      minify_html: true
  - search
  # https://squidfunk.github.io/mkdocs-material/reference/#built-in-typeset-plugin
  - typeset

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  book:
    title: Unity Catalog
    delta: https://books.japila.pl/delta-lake-internals
    spark_sql: https://books.japila.pl/spark-sql-internals
  uc:
    version: 0.4.1
    commit: https://github.com/unitycatalog/unitycatalog/commit
    github: https://github.com/unitycatalog/unitycatalog/blob/v0.4.1
    slack: https://unitycatalog.slack.com/archives
  armeria:
    # https://github.com/unitycatalog/unitycatalog/blob/v0.4.1/build.sbt#L325
    version: 1.28.4
    api: https://javadoc.io/doc/com.linecorp.armeria/armeria-javadoc/1.28.4
  delta:
    # https://github.com/unitycatalog/unitycatalog/blob/v0.4.1/build.sbt#L24
    version: 4.1.0
  hadoop:
    # https://github.com/unitycatalog/unitycatalog/blob/v0.4.1/build.sbt#L27
    version: 3.4.2
    api: https://hadoop.apache.org/docs/r3.4.2/api/index.html
  hibernate:
    # https://github.com/unitycatalog/unitycatalog/blob/v0.4.1/build.sbt#L341
    version: 6.5.0.Final
    javadoc: https://docs.jboss.org/hibernate/orm/6.5/javadocs
  iceberg:
    # https://github.com/unitycatalog/unitycatalog/blob/v0.4.1/build.sbt#L364-L367
    version: 1.9.2
    home: https://iceberg.apache.org
  java:
    # https://github.com/unitycatalog/unitycatalog/blob/v0.4.1/build.sbt#L42-L43
    version: 17
    api: https://docs.oracle.com/en/java/javase/17/docs/api/java.base
    spec: https://docs.oracle.com/javase/specs/jls/se17/html
  jcasbin:
    # https://github.com/unitycatalog/unitycatalog/blob/v0.4.1/build.sbt#L379
    version: 1.55.0
    api: https://www.javadoc.io/static/org.casbin/jcasbin/1.55.0
    github: https://github.com/casbin/jcasbin
  log4j:
    # https://github.com/unitycatalog/unitycatalog/blob/v0.4.1/build.sbt#L32
    version: 2.25.3
    manual: https://logging.apache.org/log4j/2.x/manual
  openapi:
    home: https://openapi-generator.tech
    github: https://github.com/OpenAPITools
  scala:
    # https://github.com/unitycatalog/unitycatalog/blob/v0.4.1/build.sbt#L22
    version: 2.13.17
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/books.japila.pl
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
    - icon: fontawesome/brands/medium
      link: https://jaceklaskowski.medium.com
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@jaceklaskowski
  spark:
    # https://github.com/unitycatalog/unitycatalog/blob/v0.4.1/build.sbt#L25
    # version: 4.0.0
    # This book uses a custom-built UC on Spark 4.1.1
    version: 4.1.1

# nav section is in the separate file ".nav.yml" managed by Awesome Nav for MkDocs plugin
# https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/