site_name: The Internals of Unity Catalog
site_url: https://books.japila.pl/unity-catalog-internals
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of Unity Catalog

repo_name: unity-catalog-internals
repo_url: https://github.com/japila-books/unity-catalog-internals
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate
    # https://squidfunk.github.io/mkdocs-material/upgrade/#contentcodecopy
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-path
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# https://squidfunk.github.io/mkdocs-material/customization/#additional-css
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - macros
  # https://squidfunk.github.io/mkdocs-material/reference/#built-in-meta-plugin
  - meta
  # https://squidfunk.github.io/mkdocs-material/reference/#built-in-typeset-plugin
  - typeset

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  book:
    title: Unity Catalog
    delta: https://books.japila.pl/delta-lake-internals
    spark_sql: https://books.japila.pl/spark-sql-internals
  uc:
    version: 0.3.0-SNAPSHOT
    commit: https://github.com/unitycatalog/unitycatalog/commit
    github: https://github.com/unitycatalog/unitycatalog/blob/main
  armeria:
    version: 1.28.4
    javadoc: https://javadoc.io/doc/com.linecorp.armeria/armeria-javadoc/1.28.4
  delta3:
    version: 3.2.1
  delta4:
    version: 4.0.0rc1
  hibernate:
    javadoc: https://docs.jboss.org/hibernate/orm/6.5/javadocs
  iceberg:
    home: https://iceberg.apache.org
  java:
    version: 17
    spec: https://docs.oracle.com/javase/specs/jls/se17/html
  log4j:
    version: 2.23.1
    manual: https://logging.apache.org/log4j/2.x/manual
  openapi:
    home: https://openapi-generator.tech
    github: https://github.com/OpenAPITools
  scala:
    version: 2.13
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
    - icon: fontawesome/brands/medium
      link: https://jaceklaskowski.medium.com
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@jaceklaskowski
  spark3:
    version: 3.5.3
  spark4:
    version: 4.0.0-preview1

# The sections with ... use awesome-pages plugin
# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
# Review .pages for setup
nav:
  - index.md
  - Features:
    - features/index.md
    - ... | basic-server-access-control/**.md
    - ... | docker/**.md
    - ... | iceberg/**.md
    - logging.md
    - ... | oauth2-authentication/**.md
    - ... | persistent-storage/**.md
    - ... | server-authorization/**.md
    - ... | spark-connector/**.md
  - ... | server/**.md
  - ... | cli/**.md
  - ... | client/**.md
  - ... | demo/**.md
  - ... | contenders/**.md
